using ExamDAOnAbp.QuestionBankService.EntityFrameworkCore;
using Xunit;

namespace ExamDAOnAbp.QuestionBankService.EntityFrameworkCore;

public class QuestionBankServiceEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<QuestionBankServiceEntityFrameworkCoreFixture>
{

}
