FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ExamDAOnAbp ./ExamDAOnAbp
WORKDIR /src/ExamDAOnAbp/services/Administration/src/ExamDAOnAbp.AdministrationService.HttpApi.Host
RUN dotnet publish -c Release -o bin/Release/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0  AS final
WORKDIR /app
COPY --from=build /src/ExamDAOnAbp/services/Administration/src/ExamDAOnAbp.AdministrationService.HttpApi.Host/bin/Release/publish/ .
ENTRYPOINT ["dotnet", "ExamDAOnAbp.AdministrationService.HttpApi.Host.dll"]