using ExamDAOnAbp.AdministrationService.EntityFrameworkCore;
using Xunit;

namespace ExamDAOnAbp.AdministrationService.EntityFrameworkCore;

public class AdministrationServiceEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<AdministrationServiceEntityFrameworkCoreFixture>
{

}
