using Xunit;

namespace ExamDAOnAbp.AdministrationService.EntityFrameworkCore;

[CollectionDefinition(AdministrationServiceTestConsts.CollectionDefinitionName)]
public class AdministrationServiceEntityFrameworkCoreCollection : ICollectionFixture<AdministrationServiceEntityFrameworkCoreFixture>
{

}
