using Xunit;

namespace ExamDAOnAbp.LearningOutcomeService.EntityFrameworkCore;

[CollectionDefinition(LearningOutcomeServiceTestConsts.CollectionDefinitionName)]
public class LearningOutcomeServiceEntityFrameworkCoreCollection : ICollectionFixture<LearningOutcomeServiceEntityFrameworkCoreFixture>
{

}
